### ISSUE TITLE
Extension isn't working on latest GeyserMC releases

### ISSUE THREAD

**Issue by undecimer** [GeyserExtensionists/GeyserDisplayEntity#1]
I'm using build 706

```
[12:09:47 ERROR] An exception occurred while executing event GeyserPreInitializeEvent for subscriber org.geysermc.geyser.event.GeyserEventSubscriber
java.lang.NoSuchFieldError: Class org.geysermc.geyser.registry.Registries does not have member field 'org.geysermc.geyser.registry.SimpleRegistry BEDROCK_ENTITY_IDENTIFIERS'
        at me.zimzaza4.geyserdisplayentity.ExtensionMain.registerIdentifier(ExtensionMain.java:94) ~[?:?]
        at me.zimzaza4.geyserdisplayentity.ExtensionMain.onLoad(ExtensionMain.java:89) ~[?:?]
        at org.lanternpowered.lmbda.Lmbda$1.accept(Unknown Source) ~[geyser.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.lambda$new$0(SubscriberImpl.java:55) ~[geyser.jar:?]
        at org.geysermc.event.subscribe.impl.SubscriberImpl.invoke(SubscriberImpl.java:75) ~[geyser.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fireSilently(BaseBusImpl.java:201) ~[geyser.jar:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fireSilently(OwnedEventBusImpl.java:41) ~[geyser.jar:?]
        at org.geysermc.event.bus.impl.BaseBusImpl.fire(BaseBusImpl.java:180) [geyser.jar:?]
        at org.geysermc.event.bus.impl.OwnedEventBusImpl.fire(OwnedEventBusImpl.java:41) [geyser.jar:?]
        at org.geysermc.geyser.GeyserImpl.<init>(GeyserImpl.java:216) [geyser.jar:?]
        at org.geysermc.geyser.GeyserImpl.load(GeyserImpl.java:863) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserEnable(GeyserStandaloneBootstrap.java:225) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.onGeyserInitialize(GeyserStandaloneBootstrap.java:194) [geyser.jar:?]
        at org.geysermc.geyser.platform.standalone.GeyserStandaloneBootstrap.main(GeyserStandaloneBootstrap.java:172) [geyser.jar:?]
```

**Comment by zimzaza4** [comment]
did you complie the extension by yourself?

**Comment by zimzaza4** [comment]
or the latest version which i send in my discord

**Comment by undecimer** [comment]
> did you complie the extension by yourself?

I compiled the code available here


> or the latest version which i send in my discord

I can't find an invite url to your discord

**Comment by Lklaser** [comment]
Is there any fix or way to get to the latest version?

**Comment by ksushkinSlave** [comment]
Facing the same issue, and also cant find your discord(

**Comment by AriqMicin** [comment]
> > did you complie the extension by yourself?
> 
> I compiled the code available here
> 
> > or the latest version which i send in my discord
> 
> I can't find an invite url to your discord



> Facing the same issue, and also cant find your discord(

https://discord.gg/j2R6Ee5kbE here is the discord link
